econdash:
  outputs:
    dev:
      dbname: airflow
      host: localhost
      pass: airflow
      port: 5432
      schema: econdash
      threads: 1
      type: postgres
      user: airflow
  target: dev