version: '3'
services:
  web:
    build: .
    ports:
      - "5000:8080"
    volumes:
      - .:/usr/src/app
    environment:
      - NAME=World

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=econdashdb
      - POSTGRES_USER=econdashuser
      - POSTGRES_PASSWORD=econdashpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow:
    image: apache/airflow:2.1.0
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://econdashuser:econdashpass@postgres/econdashdb
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
    ports:
      - "8080:8080"

  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:latest
    volumes:
      - ./dbt:/dbt
    working_dir: /dbt
    command: dbt run

volumes:
  postgres_data:
