version: '3.8'
services:
  web:
    build:
      context: ./web
    ports:
      - "5001:8080"
    volumes:
      - ./web:/usr/src/app
    depends_on:
      - postgres

  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: airflow
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 10s
      timeout: 5s
      retries: 5

  airflow-webserver:
    build: 
      context: ./airflow
      dockerfile: Dockerfile
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://:@redis:6379/0
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
    ports:
      - "8080:8080"
    command: /bin/bash -c "airflow db upgrade; airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin; airflow webserver"
    depends_on:
      - postgres
      - redis

  redis:
    image: redis:latest
    expose:
      - 6379

  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:latest
    volumes:
      - ./dbt:/dbt
    working_dir: /dbt
    command: dbt run
    platform: linux/amd64

volumes:
  postgres_data:
